package com.ait.test;

import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;

import com.ait.boundaries.NotificationService;
import com.ait.boundaries.UserDAO;
import com.ait.exception.UserLoginException;
import com.ait.login.LoginHandler;
import com.ait.users.User;

import static org.mockito.Matchers.isA;
import static org.mockito.Mockito.*;

public class LoginHandlerTest {

	private UserDAO userDAO;
	private NotificationService notServDAO;
	private User user;

	private LoginHandler loginHand;
	
	@Before
	public void setUP(){
		userDAO = mock(UserDAO.class);
		notServDAO = mock(NotificationService.class);
		
		loginHand = new LoginHandler(userDAO, notServDAO);		
	}
	
	@Test
	public void testNo() throws UserLoginException {
//		assertEquals(0,loginHand.login("Alan", "password"));
		verify(loginHand).login("userDAO", "notServDAO");
	}
	@Test(expected=IOException.class)
	public void UserNotFound()throws IOException{
		doThrow(new IOException()).when(userDAO).close();
		userDAO.close();
	}

}
